// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class ActivityLog
{
    public Guid ActivityLogId { get; set; }

    public Guid BatchId { get; set; }

    public int Activity { get; set; }

    public int ExecutionOrder { get; set; }

    public string UserAgent { get; set; }

    public string IpAddress { get; set; }

    public string Detail { get; set; }

    public DateTime ExecutedOn { get; set; }

    public Guid? ExecutedBy { get; set; }

    public int? ReferenceType { get; set; }

    public Guid? Reference { get; set; }

    public virtual User ExecutedByNavigation { get; set; }
}