// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace JianeTech.Data.Entities;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccessRefreshToken> AccessRefreshTokens { get; set; }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Installment> Installments { get; set; }

    public virtual DbSet<InstallmentScheme> InstallmentSchemes { get; set; }

    public virtual DbSet<InvestmentScheme> InvestmentSchemes { get; set; }

    public virtual DbSet<Investor> Investors { get; set; }

    public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserActivationToken> UserActivationTokens { get; set; }

    public virtual DbSet<UserClaim> UserClaims { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccessRefreshToken>(entity =>
        {
            entity.HasKey(e => e.TokenId);

            entity.HasIndex(e => new { e.UserId, e.UsedOn, e.InvalidatedOn }, "IX_AccessRefreshTokens_UserId_Live");

            entity.Property(e => e.TokenId)
                .HasMaxLength(64)
                .IsFixedLength();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ExpiredOn).HasColumnType("datetime");
            entity.Property(e => e.InvalidatedOn).HasColumnType("datetime");
            entity.Property(e => e.UsedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AccessRefreshTokenCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_AccessRefreshTokens_CreatedBy");

            entity.HasOne(d => d.InvalidatedByNavigation).WithMany(p => p.AccessRefreshTokenInvalidatedByNavigations)
                .HasForeignKey(d => d.InvalidatedBy)
                .HasConstraintName("FK_AccessRefreshTokens_InvalidatedBy");

            entity.HasOne(d => d.User).WithMany(p => p.AccessRefreshTokenUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccessRefreshTokens_UserId");
        });

        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.Property(e => e.ActivityLogId).ValueGeneratedNever();
            entity.Property(e => e.Detail).HasMaxLength(300);
            entity.Property(e => e.ExecutedOn).HasColumnType("datetime");
            entity.Property(e => e.IpAddress)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserAgent)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.ExecutedByNavigation).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.ExecutedBy)
                .HasConstraintName("FK_ActivityLogs_ExecutedBy");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.Property(e => e.CustomerId).ValueGeneratedNever();
            entity.Property(e => e.Address).IsRequired();
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.Customers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Customers_UserId");
        });

        modelBuilder.Entity<Installment>(entity =>
        {
            entity.Property(e => e.InstallmentId).ValueGeneratedNever();
            entity.Property(e => e.DownPayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PeriodicPayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PrincipalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReferenceBillAmount).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<InstallmentScheme>(entity =>
        {
            entity.HasKey(e => e.SchemeId);

            entity.Property(e => e.SchemeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.DownPayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PeriodicPayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PrincipalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReferenceBillAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.InstallmentSchemeCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_InstallmentSchemes_CreatedBy");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.InstallmentSchemeUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_InstallmentSchemes_UpdatedBy");
        });

        modelBuilder.Entity<InvestmentScheme>(entity =>
        {
            entity.HasKey(e => e.SchemeId);

            entity.Property(e => e.SchemeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FreeInstallationAmt).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IncomeInterest).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MinimumInvestment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Investor>(entity =>
        {
            entity.Property(e => e.InvestorId).ValueGeneratedNever();
            entity.Property(e => e.Address).IsRequired();
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.Investors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Investors_UserId");
        });

        modelBuilder.Entity<PasswordResetToken>(entity =>
        {
            entity.HasKey(e => e.TokenId);

            entity.Property(e => e.TokenId)
                .HasMaxLength(64)
                .IsFixedLength();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ExpiredOn).HasColumnType("datetime");
            entity.Property(e => e.InvalidatedOn).HasColumnType("datetime");
            entity.Property(e => e.UsedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PasswordResetTokenCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_PasswordResetTokens_CreatedBy");

            entity.HasOne(d => d.InvalidatedByNavigation).WithMany(p => p.PasswordResetTokenInvalidatedByNavigations)
                .HasForeignKey(d => d.InvalidatedBy)
                .HasConstraintName("FK_PasswordResetTokens_InvalidatedBy");

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResetTokenUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PasswordResetTokens_UserId");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(70);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(70);
            entity.Property(e => e.LockLevelResetsOn).HasColumnType("datetime");
            entity.Property(e => e.LockedUntil).HasColumnType("datetime");
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(11);
            entity.Property(e => e.Salt)
                .IsRequired()
                .HasMaxLength(80);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.InverseCreatedByNavigation)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Users_CreatedBy");

            entity.HasOne(d => d.DeletedByNavigation).WithMany(p => p.InverseDeletedByNavigation)
                .HasForeignKey(d => d.DeletedBy)
                .HasConstraintName("FK_Users_DeletedBy");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.InverseUpdatedByNavigation)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK_Users_UpdatedBy");
        });

        modelBuilder.Entity<UserActivationToken>(entity =>
        {
            entity.HasKey(e => e.TokenId);

            entity.Property(e => e.TokenId)
                .HasMaxLength(64)
                .IsFixedLength();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ExpiredOn).HasColumnType("datetime");
            entity.Property(e => e.InvalidatedOn).HasColumnType("datetime");
            entity.Property(e => e.UsedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserActivationTokenCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_UserActivationTokens_CreatedBy");

            entity.HasOne(d => d.InvalidatedByNavigation).WithMany(p => p.UserActivationTokenInvalidatedByNavigations)
                .HasForeignKey(d => d.InvalidatedBy)
                .HasConstraintName("FK_UserActivationTokens_InvalidatedBy");

            entity.HasOne(d => d.User).WithMany(p => p.UserActivationTokenUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserActivationTokens_UserId");
        });

        modelBuilder.Entity<UserClaim>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.ClaimId });

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserClaimCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_UserClaims_CreatedBy");

            entity.HasOne(d => d.DeletedByNavigation).WithMany(p => p.UserClaimDeletedByNavigations)
                .HasForeignKey(d => d.DeletedBy)
                .HasConstraintName("FK_UserClaims_DeletedBy");

            entity.HasOne(d => d.User).WithMany(p => p.UserClaimUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserClaims_UserId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}