// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class InstallmentScheme
{
    public int SchemeId { get; set; }

    public string Description { get; set; }

    public decimal PrincipalAmount { get; set; }

    public decimal DownPayment { get; set; }

    public decimal PeriodicPayment { get; set; }

    public int MonthPeriods { get; set; }

    public decimal ReferenceBillAmount { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}