// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class Installment
{
    public Guid InstallmentId { get; set; }

    public Guid SchemeId { get; set; }

    public Guid CustomerId { get; set; }

    public decimal PrincipalAmount { get; set; }

    public decimal DownPayment { get; set; }

    public decimal PeriodicPayment { get; set; }

    public int MonthPeriods { get; set; }

    public decimal? ReferenceBillAmount { get; set; }

    public int Status { get; set; }

    public int ControlNo { get; set; }
}