// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class InvestmentScheme
{
    public Guid SchemeId { get; set; }

    public int SchemeType { get; set; }

    public string Description { get; set; }

    public decimal MinimumInvestment { get; set; }

    public decimal IncomeInterest { get; set; }

    public int GracePeriodMonths { get; set; }

    public int InvestmentYears { get; set; }

    public decimal FreeInstallationAmt { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }
}