// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class PasswordResetToken
{
    public string TokenId { get; set; }

    public Guid UserId { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? ExpiredOn { get; set; }

    public DateTime? InvalidatedOn { get; set; }

    public Guid? InvalidatedBy { get; set; }

    public DateTime? UsedOn { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User InvalidatedByNavigation { get; set; }

    public virtual User User { get; set; }
}