// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class User
{
    public Guid UserId { get; set; }

    public int UserType { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public bool IsActive { get; set; }

    public int FailedLoginCount { get; set; }

    public bool IsLocked { get; set; }

    public DateTime? LockedUntil { get; set; }

    public int LockLevel { get; set; }

    public DateTime? LockLevelResetsOn { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public Guid? DeletedBy { get; set; }

    public virtual ICollection<AccessRefreshToken> AccessRefreshTokenCreatedByNavigations { get; set; } = new List<AccessRefreshToken>();

    public virtual ICollection<AccessRefreshToken> AccessRefreshTokenInvalidatedByNavigations { get; set; } = new List<AccessRefreshToken>();

    public virtual ICollection<AccessRefreshToken> AccessRefreshTokenUsers { get; set; } = new List<AccessRefreshToken>();

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual User DeletedByNavigation { get; set; }

    public virtual ICollection<InstallmentScheme> InstallmentSchemeCreatedByNavigations { get; set; } = new List<InstallmentScheme>();

    public virtual ICollection<InstallmentScheme> InstallmentSchemeUpdatedByNavigations { get; set; } = new List<InstallmentScheme>();

    public virtual ICollection<User> InverseCreatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> InverseDeletedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> InverseUpdatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<Investor> Investors { get; set; } = new List<Investor>();

    public virtual ICollection<PasswordResetToken> PasswordResetTokenCreatedByNavigations { get; set; } = new List<PasswordResetToken>();

    public virtual ICollection<PasswordResetToken> PasswordResetTokenInvalidatedByNavigations { get; set; } = new List<PasswordResetToken>();

    public virtual ICollection<PasswordResetToken> PasswordResetTokenUsers { get; set; } = new List<PasswordResetToken>();

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserActivationToken> UserActivationTokenCreatedByNavigations { get; set; } = new List<UserActivationToken>();

    public virtual ICollection<UserActivationToken> UserActivationTokenInvalidatedByNavigations { get; set; } = new List<UserActivationToken>();

    public virtual ICollection<UserActivationToken> UserActivationTokenUsers { get; set; } = new List<UserActivationToken>();

    public virtual ICollection<UserClaim> UserClaimCreatedByNavigations { get; set; } = new List<UserClaim>();

    public virtual ICollection<UserClaim> UserClaimDeletedByNavigations { get; set; } = new List<UserClaim>();

    public virtual ICollection<UserClaim> UserClaimUsers { get; set; } = new List<UserClaim>();
}