// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JianeTech.Data.Entities;

public partial class UserClaim
{
    public Guid UserId { get; set; }

    public Guid ClaimId { get; set; }

    public int Claim { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public Guid? DeletedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User DeletedByNavigation { get; set; }

    public virtual User User { get; set; }
}